### ISSUE TITLE
escaped single quote isn't recognized

### ISSUE THREAD

**Issue by mtracy** [ChemisTechlabs/dataprep-wrangler-language#1]
I am removing single quotes from a string:
```
replacepatterns col: address with: '' on: '\''
extractpatterns type: custom col: address on: /([^ ]{1,2} )*[^ ]+/ start: `{start}` end: ` `
```
The second line, as well as all below it, have the font color of a string literal. I'm assuming it is treating the escaped quote as a close quote, and the close quote as an open quote.

**Comment by guilhermecaldas** [comment]
Thank you @mtracy ! I'm going to reproduce this issue locally and map escaped characters to string blocks.

**Comment by guilhermecaldas** [comment]
@mtracy the bug has been fixed and the new version will soon be available at [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=chemistechlabs.dataprep-wrangle-language)

Please feel free to reopen this issue if your bug persists or create a new issue if you find a new one.

Thank you!

**Comment by mtracy** [comment]
:+1: perfect! Thanks so much!
